_BASE_: "/home/gaetan/hevs/implementations/object_detection/detectron2/configs/COCO-Detection/retinanet_R_50_FPN_1x.yaml"
OUTPUT_DIR: "panel_seg/panel_split/output_zou"
MODEL:
  RETINANET:
    NUM_CLASSES: 1
    NMS_THRESH_TEST: 0.1
DATASETS:
  TRAIN: ("zou_panel_splitting_train",)
  #VALIDATION: "image_clef_val"
  #TEST: ("image_clef_test",)
  TEST: ("zou_panel_splitting_test",)
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.001
#VALIDATION:
  #VALIDATION_PERIOD: 5000
TEST:
  EVAL_PERIOD: 0
  DETECTIONS_PER_IMAGE: 16
