_BASE_: "/home/gaetan/hevs/implementations/object_detection/detectron2/configs/COCO-Detection/retinanet_R_50_FPN_1x.yaml"
OUTPUT_DIR: "panel_seg/panel_splitting/output_imageclef"
MODEL:
  RETINANET:
    NUM_CLASSES: 1
    NMS_THRESH_TEST: 0.1
DATASETS:
  TRAIN: ("image_clef_train",)
  #VALIDATION: "image_clef_val"
  #TEST: ("image_clef_test",)
  TEST: ("image_clef_test",)
SOLVER:
  IMS_PER_BATCH: 4
#VALIDATION:
  #VALIDATION_PERIOD: 5000
TEST:
  EVAL_PERIOD: 0
  DETECTIONS_PER_IMAGE: 16
