_BASE_: "../utils/detectron_utils/Base-RetinaNet.yaml"
OUTPUT_DIR: "output/training/panel_splitting/output_zou"
MODEL:
  RETINANET:
    NUM_CLASSES: 1
    NMS_THRESH_TEST: 0.1
DATASETS:
  TRAIN: ("zou_panel_splitting_train",)
  #VALIDATION: "image_clef_val"
  #TEST: ("image_clef_test",)
  TEST: ("zou_panel_splitting_test",)
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.001
#VALIDATION:
  #VALIDATION_PERIOD: 5000
TEST:
  EVAL_PERIOD: 0
  DETECTIONS_PER_IMAGE: 16
