_BASE_: "../utils/detectron_utils/Base-RetinaNet.yaml"
OUTPUT_DIR: "panel_seg/label_recognition/output"
MODEL:
  RETINANET:
    NUM_CLASSES: 50
    NMS_THRESH_TEST: 0.1
DATASETS:
  TRAIN: ("zou_label_recog_train",)
  #VALIDATION: "image_clef_val"
  TEST: ("zou_label_recog_test",)
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.001
#VALIDATION:
  #VALIDATION_PERIOD: 5000
TEST:
  EVAL_PERIOD: 0
  DETECTIONS_PER_IMAGE: 16
